server:
  requestLog:
    appenders:
      - type: console
        logFormat: "%date{HH:mm:ss.SSS} [ REQUEST ] requestId=%responseHeader{X-Request-Id} request=\"%requestURL\" ip=%clientHost user=%user status=%statusCode bytes=%bytesSent duration=%elapsedTime agent=\"%header{User-Agent}\""
logging:
  loggers:
    "io.dropwizard": INFO
    "org.codi.catan":
      level: DEBUG
      additive: false
      appenders:
        - type: console
          logFormat: "%date{HH:mm:ss.SSS} [ %thread ] [ %X{requestId} ] [ %-5level ] %logger{0} - %msg%n"
  level: ERROR
  appenders:
    - type: console
      logFormat: "%date{HH:mm:ss.SSS} [ %thread ] [ %X{requestId} ] [ %-5level ] %logger - %msg%n"
swagger:
  title: "Catan Server"
  contact: "github/the-codinator"
  resourcePackage: org.codi.catan.api.health,org.codi.catan.api.user,org.codi.catan.api.game
dynamodb:
  key: ${AWS_ACCESS_KEY_ID}
  secret: ${AWS_SECRET_ACCESS_KEY}
