version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    networks:
      - catan
  server:
    image: catan-server
    ports:
      - '8080:8080'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - catan
    depends_on:
      - dynamodb
