version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
  catan:
    image: catan-server
    ports:
      - '8080:8080'
    environment:
      - JDK_JAVA_OPTIONS=-Xmx512m -Xms512m
      - CATAN_DATABASE_TYPE=dynamoDb
      - CATAN_AWS_ACCESS_KEY_ID=fakeKey
      - CATAN_AWS_SECRET_ACCESS_KEY=fakeSecret
    depends_on:
      - dynamodb
